Update basic examples with namespaces
HEP-FCC/FCCAnalyses pull request #82
Opened 2021-03-17 14:17 UTC by bistapf

Updated the C++ analyzers code to the namespace format and adjusted basic example & documentation accordingly. Also included overview table + brief explanation of common functions used in readme.

2021-03-22 08:11 UTC, clementhelsens commented
Thanks @bistapf , I ping @EmanuelPerez , @gganis , @patriziaazzi because I'll have very little time to look at this.

2021-03-22 08:45 UTC, patriziaazzi commented
I cannot merge this pull request.

2021-03-22 10:24 UTC, clementhelsens commented
I could hit the merge button for the time being no problem. But this PR needs to be reviewed before I think.

Le 22 mars 2021 à 09:45, Patrizia Azzi ***@***.******@***.***>> a écrit :



I cannot merge this pull request.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/HEP-FCC/FCCAnalyses/pull/82#issuecomment-803878314>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABIGGDK7K2I7PIOLQGQYKI3TE37UFANCNFSM4ZKVVCGA>.

2021-03-22 10:28 UTC, patriziaazzi commented
yes. I just sent the message bc I did not even had the possibility to merge.

Pat

Le 22 mars 2021 à 11:24, Clement Helsens ***@***.******@***.***>> a écrit :


I could hit the merge button for the time being no problem. But this PR needs to be reviewed before I think.

Le 22 mars 2021 à 09:45, Patrizia Azzi ***@***.******@***.***>> a écrit :



I cannot merge this pull request.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/HEP-FCC/FCCAnalyses/pull/82#issuecomment-803878314>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABIGGDK7K2I7PIOLQGQYKI3TE37UFANCNFSM4ZKVVCGA>.


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/HEP-FCC/FCCAnalyses/pull/82#issuecomment-803950993>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABKTDT2AGVFSB2KWFY7YKLDTE4LHDANCNFSM4ZKVVCGA>.

2021-03-22 11:56 UTC, gganis requested changes
Thanks, It looks good to me. Please fix the links to ReconstructedParticle.h and MCParticle.h (see specific comment).

2021-03-22 11:56 UTC, gganis commented on examples/basics/README.md
> +Below you can find an overview of the basic, most commonly required functions, to illustrate the naming conventions. This is not an exhaustive list, if you want to find out all functions that are ava
Here there two links to a prvate repository (bistapf). Can these point to the files in the official directory? (If there are changes to those files, the changes should be perhaps parts of the PR?)

2021-03-23 09:12 UTC, gganis commented on examples/basics/README.md
> +Below you can find an overview of the basic, most commonly required functions, to illustrate the naming conventions. This is not an exhaustive list, if you want to find out all functions that are ava
I can fix the links after the merge.

2021-03-23 09:12 UTC, merged